# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Production Setings
#
# Run during the 'gulp build' command, default for github pages.

# GitHub Page Overrides
#
#safe: true
#lsi: false
#source: your top-level directory

# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: เทพโค้ด ดอท คอม
tagline: "รู้จริง อินเทรนด์ เข้มข้น"
description: "บล็อกความรู้จากประสบการณ์จริง"
url: https://lnwkodedotcom.github.io/

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
#source: root directory
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: zarazi
  email: zarazi@hotmail.com
  bio: live long coder
  twitter: https://twitter.com/iamisara

# general setting for Jekyll
#
# Hides your drafts and future posts
future: false
show_drafts: false

# Gives you more accurate related posts
lsi: true

# Removes the upper limit for posts generated
limit_posts: 0

# Permalink structure and pagination options
relative_permalinks: true
permalink: /:categories/:title/
paginate: 7
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: pygments

# Exclude these files from your production _site
exclude:
    - node_modules
    - site
    - bower.json
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - package.json
    - LICENSE
    - README.md

#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
googleAnalytics: UA-XXXXX-X
